[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# MAKES COMPILATION VERY SLOW!!
# ir optimizer
# viaIR = true 
optimizer_runs = 10 #200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
